//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CVEntities3 : DbContext
    {
        public DB_CVEntities3()
            : base("name=DB_CVEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_About> tbl_About { get; set; }
        public virtual DbSet<tbl_Certificates> tbl_Certificates { get; set; }
        public virtual DbSet<tbl_Contact> tbl_Contact { get; set; }
        public virtual DbSet<tbl_Education> tbl_Education { get; set; }
        public virtual DbSet<tbl_Experience> tbl_Experience { get; set; }
        public virtual DbSet<tbl_Skills> tbl_Skills { get; set; }
        public virtual DbSet<tbl_Languages> tbl_Languages { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
    }
}
