//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Education
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Subtitle1 { get; set; }
        public string Subtitle2 { get; set; }
        public string Description { get; set; }
        public string GNA { get; set; }
        public string Date { get; set; }
    }
}
